services:
  vpr_hacker:
    build: telegram_bot
    ports:
      - "8080:8080"
    environment:
      - TOKEN=${BOT_TOKEN}
      - POSTGRES_CONN=${POSTGRES_CONN}
      - LOGGER_LEVEL=${LOGGER_LEVEL}
    depends_on:
      - postgres_hacker

  postgres_hacker:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5432:5432"
    volumes:
      - postgres_volume_sdamgia:/data

volumes:
  postgres_volume_sdamgia:
